# Generated by Django 5.2.1 on 2025-05-29 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='ID phiên')),
                ('user_message', models.TextField(verbose_name='Tin nhắn người dùng')),
                ('bot_response', models.TextField(verbose_name='Phản hồi bot')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='Điểm tin cậy')),
                ('response_time', models.FloatField(default=0.0, verbose_name='Thời gian phản hồi (s)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP người dùng')),
            ],
            options={
                'verbose_name': 'Lịch sử chat',
                'verbose_name_plural': 'Lịch sử chat',
                'db_table': 'chat_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Câu hỏi')),
                ('answer', models.TextField(verbose_name='Câu trả lời')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Danh mục')),
                ('embedding_id', models.IntegerField(blank=True, null=True, verbose_name='ID embedding')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Cơ sở tri thức',
                'verbose_name_plural': 'Cơ sở tri thức',
                'db_table': 'knowledge_base',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('like', 'Thích'), ('dislike', 'Không thích'), ('report', 'Báo cáo')], max_length=10)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Bình luận')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='knowledge.chathistory')),
            ],
            options={
                'verbose_name': 'Phản hồi người dùng',
                'verbose_name_plural': 'Phản hồi người dùng',
                'db_table': 'user_feedback',
            },
        ),
    ]
