# Generated by Django 5.2.1 on 2025-05-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='entities',
            field=models.JSONField(blank=True, help_text='Extracted entities', null=True),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='intent',
            field=models.CharField(blank=True, help_text='Detected intent', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='method',
            field=models.CharField(blank=True, help_text='Response generation method', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='strategy',
            field=models.CharField(blank=True, help_text='Response strategy used', max_length=50, null=True),
        ),
    ]
