# Generated by Django 5.2.1 on 2025-06-25 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_add_user_to_chathistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='session_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề phiên chat'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['user', 'session_id'], name='idx_user_session'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['user', '-timestamp'], name='idx_user_timestamp'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['session_id', '-timestamp'], name='idx_session_timestamp'),
        ),
    ]
