# Generated by Django 5.2.1 on 2025-06-22 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaentry',
            name='stt',
            field=models.CharField(help_text='Số thứ tự/ID (ví dụ: TB_1252) - Có thể trùng lặp', max_length=50, validators=[django.core.validators.RegexValidator(message='STT chỉ được chứa chữ cái, số, dấu _ và -', regex='^[A-Za-z0-9_-]+$')], verbose_name='STT'),
        ),
    ]
