# Generated by Django 5.2.1 on 2025-06-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='chatbot_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Lưu các tùy chọn cá nhân hóa chatbot', verbose_name='Tùy chọn chatbot'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='office_room',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phòng làm việc'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='position',
            field=models.CharField(choices=[('giang_vien', 'Giảng viên'), ('tro_giang', 'Trợ giảng'), ('truong_khoa', 'Trưởng khoa'), ('pho_truong_khoa', 'Phó trưởng khoa'), ('truong_bo_mon', 'Trưởng bộ môn'), ('can_bo', 'Cán bộ'), ('admin', 'Quản trị viên')], default='giang_vien', max_length=20, verbose_name='Chức vụ'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='specialization',
            field=models.TextField(blank=True, verbose_name='Chuyên môn/Lĩnh vực nghiên cứu'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('cntt', 'Công nghệ thông tin'), ('duoc', 'Dược'), ('dien_tu', 'Điện tử viễn thông'), ('co_khi', 'Cơ khí'), ('kinh_te', 'Kinh tế'), ('luat', 'Luật'), ('y_khoa', 'Y khoa'), ('ngoai_ngu', 'Ngoại ngữ'), ('xay_dung', 'Xây dựng'), ('quan_tri', 'Quản trị kinh doanh'), ('ke_toan', 'Kế toán'), ('marketing', 'Marketing'), ('tai_chinh', 'Tài chính ngân hàng'), ('general', 'Chung (không chuyên ngành)')], default='general', help_text='Khoa/Ngành chuyên môn', max_length=20),
        ),
    ]
