# Generated by Django 5.2.1 on 2025-11-19 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_faculty_gender'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='faculty',
            managers=[
            ],
        ),
    ]
